// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3dhi95s0Z-qgRP1dHPHahfk9GcdxQyQY',
    appId: '1:896259964332:web:9d401f2bc0d0262f1d8e09',
    messagingSenderId: '896259964332',
    projectId: 'rebay-project',
    authDomain: 'rebay-project.firebaseapp.com',
    storageBucket: 'rebay-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTTVEoo3CkuyR1tFAOYXz0__GPtd5SQFE',
    appId: '1:896259964332:android:966cffa254d2da041d8e09',
    messagingSenderId: '896259964332',
    projectId: 'rebay-project',
    storageBucket: 'rebay-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8MSg-crfZhlYIBq5sqRW2NfxqcExKOUM',
    appId: '1:896259964332:ios:962a29211e1edd2b1d8e09',
    messagingSenderId: '896259964332',
    projectId: 'rebay-project',
    storageBucket: 'rebay-project.firebasestorage.app',
    iosBundleId: 'com.example.rebay',
  );
}
